#!/bin/sh

output_config() {
    echo "graph_title DNS cache insertions"
    echo "graph_vlabel DNS cache insertions"
    echo "graph_category pi-hole"
    echo "insertions.draw AREA"
    echo "evictions.draw STACK"
    echo "insertions.label insertions"
    echo "evictions.label evictions"
    echo "graph_args --base 1000 -l 0"
}

output_values() {
	  INSERTIONS=$(dig +short chaos txt insertions.bind | sed 's/"//g')
	  EVICTIONS=$(dig +short chaos txt evictions.bind | sed 's/"//g')
    printf "insertions.value $INSERTIONS\n"
    printf "evictions.value $EVICTIONS\n"
}

output_usage() {
    printf >&2 "%s - zeigt die DNS cache insertions und evictions\n" ${0##*/}
    printf >&2 "Usage: %s [config]\n" ${0##*/}
}

case $# in
    0)
        output_values
        ;;
    1)
        case $1 in
            config)
                output_config
                ;;
            *)
                output_usage
                exit 1
                ;;
        esac
        ;;
    *)
        output_usage
        exit 1
        ;;
esac
