#!/bin/sh

output_config() {
    echo "graph_title DNS latency"
    echo "graph_vlabel DNS latency 24 hours"
    echo "graph_category pi-hole"
    echo "median.draw LINE"
    echo "average.draw LINE"
    echo "median.label median"
    echo "average.label avg"
    echo "graph_args --base 1000 -l 0 --upper-limit 200"
}

output_values() {
    MEDIAN=$(grep -a `date +%Y-%m-%d` /var/log/dnscrypt-proxy/query.log | grep [0-9][0-9]ms | cut -f 6 | tr -d ms | sort -n | awk ' { a[i++]=$1; } END { x=int((i+1)/2); if (x < (i+1)/2) print (a[x-1]+a[x])/2; else print a[x-1]; }')
	AVG=$(grep -a `date +%Y-%m-%d` /var/log/dnscrypt-proxy/query.log | grep [0-9][0-9]ms | cut -f 6 | tr -d ms | sort -n | awk '{ total += $1; count++ } END { printf "%.0f",total/count }')
    printf "median.value $MEDIAN\n"
    printf "average.value $AVG\n"
}

output_usage() {
    printf >&2 "%s - shows DNS latency of the last 24 hours\n" ${0##*/}
    printf >&2 "Usage: %s [config]\n" ${0##*/}
}

case $# in
    0)
        output_values
        ;;
    1)
        case $1 in
            config)
                output_config
                ;;
            *)
                output_usage
                exit 1
                ;;
        esac
        ;;
    *)
        output_usage
        exit 1
        ;;
esac
