#!/bin/sh

output_config() {
    echo "graph_category pi-hole"
    echo "graph_title DNS queries"
    echo "graph_vlabel DNS queries"
    echo "graph_args --base 1000 -l 0 --upper-limit 30000 --rigid"
    echo "graph_scale yes"
    echo "query.draw AREA"
    echo "query.label queries"
    echo "forwarded.draw STACK"
    echo "forwarded.label forwarded"
    echo "cached.draw STACK"
    echo "cached.label cached"
}

output_values() {
    printf "query.value %d\n" "`grep query /var/log/pihole.log | wc -l`"
    printf "forwarded.value %d\n" "`grep forwarded /var/log/pihole.log | wc -l`"
    printf "cached.value %d\n" "`grep cached /var/log/pihole.log | wc -l`"
}

output_usage() {
    printf >&2 "%s - Shows DNS queries within 24 hours\n" ${0##*/}
    printf >&2 "Usage: %s [config]\n" ${0##*/}
}

case $# in
    0)
        output_values
        ;;
    1)
        case $1 in
            config)
                output_config
                ;;
            *)
                output_usage
                exit 1
                ;;
        esac
        ;;
    *)
        output_usage
        exit 1
        ;;
esac
